apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wg-landing-page
labels:
- pairs:
    app.env: production
    app.owner: wgroup
    app.project: wg-landing-page
resources:
- deployment.yaml
- service.yaml
images:
- name: 717581138308.dkr.ecr.ap-southeast-1.amazonaws.com/wg-landing-page-app
  newTag: 729b980d
