default:
  image: alpine:latest
  interruptible: true
  timeout: 90m
  tags:
    - wg-project

variables:
  APP_NAME: wg-landing-page-app
  CI_REGISTRY_IMAGE: "${ECR_REPOSITORY_URL}/${APP_NAME}"
  PROD_DEPLOYMENT_GIT_URL: gitlab.com/siam-intelligence-technology/wg-project/web-wg-management/wg-landing-page.git

stages:
  - build_and_push_ecr
  - deploy-prod

build_and_push_ecr:
  stage: build_and_push_ecr
  variables:
    AWS_ACCESS_KEY_ID: ${CI_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${CI_AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: ${CI_AWS_DEFAULT_REGION}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor 
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/deployment/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
  when: manual

deploy-prod:
  stage: deploy-prod
  image: alpine:latest
  before_script:
    - apk add --no-cache git curl bash
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - mv kustomize /usr/local/bin/
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "GitLab CI/CD"
  script:
    - git clone https://${CI_USERNAME}:${CI_PUSH_TOKEN}@$PROD_DEPLOYMENT_GIT_URL
    - cd wg-landing-page
    - git checkout -B main
    - git pull origin main
    - cd deployment/production
    - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - cat kustomization.yaml
    - git commit -am '[skip ci] PROD image tag $CI_COMMIT_SHORT_SHA updated!!'
    - git push origin main
  only:
    - main
  when: manual